from io import StringIO
from unittest import mock
import unittest

from vine.ReviewRule import ApproveInputSpec, ReviewRule
from vine.approve import Approve


class FakeCommit:
    def __init__(self, commit_id, short_id, committed_date, title):
        self.id = commit_id
        self.short_id = short_id
        self.committed_date = committed_date
        self.title = title


class FakeReviewRequest:
    def __init__(self, description):
        self._description = description

    def author(self):
        return "someone_else"

    def fromRef(self):
        return "feature/topic"

    def fromSHA(self):
        return "abcdef1234567890"

    def link(self):
        return "https://gitlab.example/mr/42"

    def commits(self):
        return [
            FakeCommit(
                "abcdef1234567890",
                "abcdef12",
                "2026-04-30T12:00:00+00:00",
                "Add feature work"
            )
        ]

    def description(self):
        return self._description


class FakeReviewRuleManager:
    def get_default_rule(self):
        return None

    def get_rule(self, rule_name):
        return None


class TestApprove(unittest.TestCase):

    def testGetApproveInputPrintsExistingMergeRequestValue(self):
        rule = ReviewRule(
            name="qa",
            label="QA Review",
            eligibleReviewers=[".+"] ,
            repositories=[".+"] ,
            approveActions=["description"],
            approveInputSpecs=[
                ApproveInputSpec(
                    source="prompt",
                    prompt="Enter the QA ticket:",
                    label="QA Ticket",
                    include_in_description=True,
                    include_in_tag=False
                )
            ]
        )

        description = """Existing description

# GRAPE

Generated by GRAPE test.

## Related Reviews

None

## Review Rules

### QA Review

Reviewer(s): reviewer

#### repo1

* QA Ticket: QA-1234
"""

        modified_repos = {
            "repo1": {
                "review_request": FakeReviewRequest(description)
            }
        }

        stdout = StringIO()

        with mock.patch("vine.utility.userInput", return_value="y"), \
             mock.patch("builtins.input", return_value="QA-5678"), \
             mock.patch("sys.stdout", stdout):
            approve_input = Approve._get_approve_input(
                rule,
                "reviewer",
                "feature/topic",
                modified_repos,
                FakeReviewRuleManager()
            )

        output = stdout.getvalue()

        self.assertIn("Existing merge request value:", output)
        self.assertIn("QA-1234", output)
        self.assertEqual("QA-5678", approve_input["repo1"]["approve_inputs"][0]["value"])
