from unittest import mock
import unittest

from vine.PullRequestDescriptionModel import PullRequestDescriptionModel


class FakeReviewRuleManager:

    def get_default_rule(self):
        return None

    def get_rule(self, rule_name):
        return None


class TestPullRequestDescriptionModel(unittest.TestCase):

    def testToTextTrimsExtraBlankLinesBeforeGrapeSection(self):
        model = PullRequestDescriptionModel(
            userLines=[
                "SUMMARY: Updated XML handling.",
                "",
                "DETAILS:",
                "",
                "* Add Array and Column tags",
                "",
                "",
                "",
            ],
            relatedReviews=set(),
            reviewRules={}
        )

        with mock.patch("vine.PullRequestDescriptionModel.version.grapeVersion", return_value="test"):
            description = model.to_text()

        self.assertIn("* Add Array and Column tags\n\n# GRAPE", description)
        self.assertNotIn("* Add Array and Column tags\n\n\n# GRAPE", description)

    def testFromTextRoundTripTrimsExtraBlankLinesBeforeGrapeSection(self):
        original_description = """SUMMARY: Updated XML handling.

DETAILS:

* Add Array and Column tags




# GRAPE

Generated by GRAPE test.

## Related Reviews

None
"""

        model = PullRequestDescriptionModel.from_text(
            original_description,
            FakeReviewRuleManager()
        )

        with mock.patch("vine.PullRequestDescriptionModel.version.grapeVersion", return_value="test"):
            description = model.to_text()

        self.assertIn("* Add Array and Column tags\n\n# GRAPE", description)
        self.assertNotIn("* Add Array and Column tags\n\n\n# GRAPE", description)
