from unittest import mock
import unittest

from vine.PullRequestDescriptionModel import PullRequestDescriptionModel


class FakeReviewRuleManager:

    def get_default_rule(self):
        return None

    def get_rule(self, rule_name):
        return None


class TestPullRequestDescriptionModel(unittest.TestCase):

    def testToTextTrimsExtraBlankLinesBeforeGrapeSection(self):
        """Verify generated descriptions keep one blank line before # GRAPE."""
        model = PullRequestDescriptionModel(
            userLines=[
                "SUMMARY: Updated a generic feature.",
                "",
                "DETAILS:",
                "",
                "* Add a generic implementation detail",
                "",
                "",
                "",
            ],
            relatedReviews=set(),
            reviewRules={}
        )

        with mock.patch("vine.PullRequestDescriptionModel.version.grapeVersion", return_value="test"):
            description = model.to_text()

        self.assertIn("* Add a generic implementation detail\n\n# GRAPE", description)
        self.assertNotIn("* Add a generic implementation detail\n\n\n# GRAPE", description)

    def testFromTextRoundTripTrimsExtraBlankLinesBeforeGrapeSection(self):
        """Verify existing descriptions are normalized when regenerated."""
        original_description = """SUMMARY: Updated a generic feature.

DETAILS:

* Add a generic implementation detail




# GRAPE

Generated by GRAPE test.

## Related Reviews

None
"""

        model = PullRequestDescriptionModel.from_text(
            original_description,
            FakeReviewRuleManager()
        )

        with mock.patch("vine.PullRequestDescriptionModel.version.grapeVersion", return_value="test"):
            description = model.to_text()

        self.assertIn("* Add a generic implementation detail\n\n# GRAPE", description)
        self.assertNotIn("* Add a generic implementation detail\n\n\n# GRAPE", description)

    def testStackMetadataRoundTripsWithoutReplacingUserText(self):
        """Generated vertical relationships retain stable machine metadata."""
        metadata = {
            "stack_id": "stack-1",
            "stack": "widgets",
            "level_id": "level-2",
            "level": "api",
            "position": 2,
            "total": 3,
            "destination": "develop",
            "depends_on": "https://example.test/mr/1",
        }
        model = PullRequestDescriptionModel(
            userLines=["Keep this user-authored summary."],
            stackMetadata=metadata)

        with mock.patch(
                "vine.PullRequestDescriptionModel.version.grapeVersion",
                return_value="test"):
            description = model.to_text()
        parsed = PullRequestDescriptionModel.from_text(
            description, FakeReviewRuleManager())

        self.assertEqual(metadata, parsed.stackMetadata)
        self.assertEqual(
            "Keep this user-authored summary.", parsed.userLines[0])
