include:
  - .gitlab/rules.yml
  - .gitlab/runners.yml
  - .gitlab/test_LC.yml
  - .gitlab/test_Windows.yml

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test

test-all_rzgenie:
  stage: test
  timeout: 30 minutes 
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "2"
  extends:
    - .run_on_merge_request
    - .run_rzgenie_shell
    - .test_linux
  interruptible: true

test-Windows:
  stage: test
  timeout: 30 minutes
  variables:
    GIT_DEPTH: "2"
  extends:
    - .run_manually
    - .run_ale3d_windows
    - .test_Windows
  interruptible: false
