include:
  - .gitlab/rules.yml
  - .gitlab/runners.yml
  - .gitlab/test_LC.yml
  - .gitlab/test_Windows.yml

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test

+ Run Grape Publish (add to merge train):
  stage: test
  timeout: 30 minutes 
  variables:
    GIT_STRATEGY: clone
  extends:
    - .run_manually_on_merge_request
    - .run_rzwhippet_shell
  script:
    - if [ "$CI_MERGE_REQUEST_APPROVED" != "true" ] ; then echo "Merge request must be approved by reviewers!"; exit 1 ; fi
    - git remote set-url origin ssh://git@rzgitlab.llnl.gov:7999/GRP/grape.git
    - $CI_PROJECT_DIR/grape -d checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - $CI_PROJECT_DIR/grape -d publish

merge_train_ticket:
  stage: test
  timeout: 30 minutes 
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "2"
  extends:
    - .run_on_merge_request_except_on_changes_to_update_logs
    - .run_rzwhippet_shell
    - .test_linux
  interruptible: true

all_aboard_the_merge_train:
  stage: test
  timeout: 30 minutes
  variables:
    GIT_STRATEGY: none
  extends:
    - .run_on_merge_request_changes_to_update_logs
    - .run_rzwhippet_shell
    - .auto_pass
  interruptible: true


merge_train:
  stage: test
  timeout: 30 minutes
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "2"
  extends:
    - .run_on_merge_train_changes_to_update_logs
    - .run_rzwhippet_shell
    - .test_linux
  interruptible: true

tag_pushes_to_develop_or_master:
  stage: test
  timeout: 30 minutes
  variables:
    GIT_STRATEGY: clone
  extends:
    - .run_on_push_to_develop_or_master
    - .run_rzwhippet_shell
    - .tick_version
  interruptible: false

do_not_push_the_button_before_grape_publish:
  stage: test
  timeout: 30 minutes
  variables:
    GIT_STRATEGY: none
  extends:
    - .run_on_merge_train_if_no_changes_to_update_logs
    - .run_rzwhippet_shell
    - .auto_fail
  interruptible: true

# deactivated until we have a gitlab windows runner for grape
test-Windows:
  stage: test
  timeout: 30 minutes
  variables:
    GIT_DEPTH: "2"
  extends:
    - .run_never
    - .run_ale3d_windows
    - .test_Windows
  interruptible: false
