include:
  - .gitlab/artifacts.yml
  - .gitlab/rules.yml
  - .gitlab/runners.yml
  - .gitlab/test_LC.yml
  - .gitlab/test_Windows.yml

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test

test-all_rzgenie:
  stage: test
  timeout: 15 minutes 
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
  extends:
    - .cache_linux_build_pull
    - .run_on_merge_request
    - .run_rzgenie_shell
    - .test_linux
  interruptible: true

test-Windows:
  stage: test
  timeout: 15 minutes
  extends:
    - .cache_window_build_pull
    - .run_on_merge_request_unapproved_or_grape_commit_manually
    - .test_Windows
  interruptible: false
