import json
import logging
import os
import shutil
import stat
from vine import addSubproject
from vine import checkout
from vine import config_parser_global
from vine import config_parser_user
from vine import config_parser_workspace
from vine import grape_errors
from vine import grapeGit as git
from vine import multi_repo_cmd_launcher
from vine import utility
from vine.vine_logging import log_wrapper
from vine.workspace_dir_handler import WorkspaceDirHandler
from vine.option import Option

try:
    import tkinter as Tk
    TkinterImportError = None
except ImportError as e:
    TkinterImportError = e


# update your custom sparse checkout view
class UpdateView(Option, WorkspaceDirHandler):
    """
    grape uv  - Updates your active submodules and ensures you are on a consistent branch throughout your project.
    Usage: grape-uv [-f] [--checkSubprojects] [-b] [--skipTopLevel] [--skipSubmodules] [--allSubmodules] [--gui]
                    [--skipNestedSubprojects] [--allNestedSubprojects] [--sync=<bool>] [--branchName=<branchName>]
                    [--add=<addedSubmoduleOrSubproject>...] [--rm=<removedSubmoduleOrSubproject>...]
                    [--generateSHAList] [--ensureCIReposPresent] [--verifySHAList]

    Options:
        -f                       Force removal of subprojects currently in your view that are taken out of the view as a
                                 result to this call to uv.
        --checkSubprojects       Checks for branch model consistency across your submodules and subprojects, but does
                                 not go through the 'which submodules do you want' script.
        -b                       Automatically creates subproject branches that should be there according to your branching
                                 model.
        --skipTopLevel           Skip top level repository for syncing and checking.
        --skipSubmodules         Skip all submodules.
        --allSubmodules          Automatically add all submodules to your workspace.
        --skipNestedSubprojects  Skip all nested subprojects.
        --allNestedSubprojects   Automatically add all nested subprojects to your workspace.
        --sync=<bool>            Take extra steps to ensure the branch you're on is up to date with origin,
                                 either by pushing or pulling the remote tracking branch.
                                 This will also checkout the public branch in a headless state prior to offering to create
                                 a new branch (in repositories where the current branch does not exist).
                                 [default: .grapeconfig.post-checkout.syncWithOrigin]
        --branchName=<name>      Override the branch name
        --add=<project>          Submodule or subproject to add to the workspace. Can be defined multiple times.
        --rm=<project>           Submodule or subproject to remove from the workspace. Can be defined multiple times.
        --gui                    Use the graphical user interface to select your view.
        --generateSHAList        Dump current nested subproject and topLevel repo SHAs to GRAPE_PROJECT_SHA.json.
        --verifySHAList          Verify current state is consistent with state in a file generated by --gnerateSHAList.
        --ensureCIReposPresent   Ensure any repos listed in .grapeconfig.workspace.CIRepos are present in the workspace
    """
    def __init__(self):
        super(UpdateView, self).__init__()
        self._key = "uv"
        self._section = "Workspace"
        self._pushBranch = False
        self._skipPush = False
        self.uvManager = None

    def description(self):
        return "Update the view of your current working tree"

    def defineActiveSubprojects(self, projectType="submodule"):
        """
        Queries the user for the submodules (projectType == "submodule") or nested subprojects
        (projectType == "nested subproject") they would like to activate.

        """
        if projectType == "submodule":
            allSubprojects = git.getAllSubmodules(execution_path=self.workspace_dir)
            activeSubprojects = git.getActiveSubmodules(execution_path=self.workspace_dir)

        if projectType == "nested subproject":
            config = config_parser_global.grapeConfig()
            allSubprojectNames = config.getAllNestedSubprojects()
            allSubprojects = []
            for project in allSubprojectNames:
                allSubprojects.append(config.get(f"nested-{project}", "prefix"))
            activeSubprojects = config_parser_user.getAllActiveNestedSubprojectPrefixes(workspaceDir=self.workspace_dir)

        toplevelDirs = {}
        toplevelActiveDirs = {}
        toplevelSubs = []
        for sub in allSubprojects:
            # we are taking advantage of the fact that branchPrefixes are the same as directory prefixes for local
            # top-level dirs.
            prefix = git.branchPrefix(sub)
            if sub != prefix:
                toplevelDirs[prefix] = []
                toplevelActiveDirs[prefix] = []
        for sub in allSubprojects:
            prefix = git.branchPrefix(sub)
            if sub != prefix:
                toplevelDirs[prefix].append(sub)
            else:
                toplevelSubs.append(sub)
        for sub in activeSubprojects:
            prefix = git.branchPrefix(sub)
            if sub != prefix:
                toplevelActiveDirs[prefix].append(sub)

        included = {}

        if self.uvManager:
            self.uvManager.createFrame(projectType)

        for directory, subprojects in toplevelDirs.items():

            activeDir = toplevelActiveDirs[directory]
            if len(activeDir) == 0:
                defaultValue = "none"
            elif set(activeDir) == set(subprojects):
                defaultValue = "all"
            else:
                defaultValue = "some"

            if self.uvManager:
                opt = "s"
                self.uvManager.createSection(directory)
            else:
                opt = utility.userInput(f"Would you like all, some, or none of the {projectType}s in {directory}?",
                                        default=defaultValue)

            if opt.lower()[0] == "a":
                for subproject in subprojects:
                    included[subproject] = True

            if opt.lower()[0] == "n":
                for subproject in subprojects:
                    included[subproject] = False
            if opt.lower()[0] == "s":
                for subproject in sorted(subprojects, key=lambda v: (v.upper(), v[0].islower())):
                    if self.uvManager:
                        # Set the default value for the gui
                        subIsActive = subproject in activeSubprojects
                        included[subproject] = subIsActive
                        # subproject always uses "/" even on Windows
                        bareSubproject = subproject.partition(directory + "/")[2]
                        self.uvManager.createEntry(directory, bareSubproject, subIsActive)
                    else:
                        included[subproject] = utility.userInput(f"Would you like {projectType} {subproject}? [y/n]",
                                                                 'y' if (subproject in activeSubprojects) else 'n')
        if self.uvManager and toplevelSubs:
            self.uvManager.createSection()
        for subproject in sorted(toplevelSubs, key=lambda v: (v.upper(), v[0].islower())):
            if self.uvManager:
                # Set the default value for the gui
                subIsActive = subproject in activeSubprojects
                included[subproject] = subIsActive
                self.uvManager.createEntry("", subproject, subIsActive)
            else:
                included[subproject] = utility.userInput(f"Would you like {projectType} {subproject}? [y/n]",
                                                         'y' if (subproject in activeSubprojects) else 'n')
        return included

    def defineActiveNestedSubprojects(self):
        """
        Queries the user for the nested subprojects they would like to activate.

        """
        return self.defineActiveSubprojects(projectType="nested subproject")


    def verifySHAList(self, sha_dict):
        active_nested_subprojects = config_parser_user.getAllActiveNestedSubprojectPrefixes(workspaceDir=self.workspace_dir)
        config = config_parser_global.grapeConfig()
        CISubprojects = config.get("workspace","CIRepos").split(' ')
        valid = True
        for sub in CISubprojects:
            our_sha = git.SHA(execution_path=os.path.join(self.workspace_dir,sub))
            if sha_dict[sub] == our_sha:
                logging.info(f"subproject {sub} matches versions ({sha_dict[sub]})")
            else:
                valid = False
                logging.info(f"subproject {sub} at {our_sha}, expected at {sha_dict[sub]}")
                break
        return valid


    @log_wrapper
    def execute(self, args):
        config = config_parser_global.grapeConfig()
        if args["--gui"] and TkinterImportError:
            logging.error("grape uv --gui requires Tkinter.\n  The following error was raised during the import:\n\n%s\n" % TkinterImportError)
            return True

        if args["--verifySHAList"]:
            with open(os.path.join(self.workspace_dir,"GRAPE_PROJECT_SHA.json"),'r') as f:
                sha_dict = json.load(f)
            return self.verifySHAList(sha_dict)

        sync = args["--sync"].lower().strip() in ["true", "yes"]
        args["--sync"] = sync
        base = git.baseDir(execution_path=self.workspace_dir)
        if base == "":
            return False
        hasSubmodules = len(git.getAllSubmodules(execution_path=self.workspace_dir)) > 0 and not args["--skipSubmodules"]
        includedSubmodules = {}
        includedNestedSubprojectPrefixes = {}

        allSubmodules = git.getAllSubmodules(execution_path=self.workspace_dir)
        allNestedSubprojects = config.getAllNestedSubprojects()

        addedSubmodules = []
        addedNestedSubprojects = []
        addedProjects = args["--add"]
        if args["--ensureCIReposPresent"]:
            CIRepos = config.get("workspace","CIRepos").split(' ')
            addedProjects = addedProjects + CIRepos
        notFound = []

        for proj in addedProjects:
            if proj in allSubmodules:
                addedSubmodules.append(proj)
            elif proj in allNestedSubprojects:
                addedNestedSubprojects.append(proj)
            else:
                notFound.append(proj)

        rmSubmodules = []
        rmNestedSubprojects = []
        rmProjects = args["--rm"]

        for proj in rmProjects:
            if proj in allSubmodules:
                rmSubmodules.append(proj)
            elif proj in allNestedSubprojects:
                rmNestedSubprojects.append(proj)
            else:
                notFound.append(proj)

        if notFound:
            logging.info(f"\"{','.join(notFound)}\" not found in submodules {','.join(allSubmodules)} \nor\n nested subprojects {','.join(allNestedSubprojects)}")
            return False

        if not args["--checkSubprojects"]:
            root = None
            if args["--gui"]:
                root = Tk.Tk()
                root.title("GRAPE uv - select active subprojects")
                self.uvManager = UVManager(master=root)

            # get submodules to update
            if hasSubmodules:
                if args["--allSubmodules"]:
                    includedSubmodules = {sub:True for sub in allSubmodules}
                elif args["--add"] or args["--rm"] or args["--ensureCIReposPresent"]:
                    includedSubmodules = {sub:True for sub in git.getActiveSubmodules(execution_path=self.workspace_dir)}
                    includedSubmodules.update({sub:True for sub in addedSubmodules})
                    includedSubmodules.update({sub:False for sub in rmSubmodules})
                else:
                    includedSubmodules = self.defineActiveSubprojects()

            # get subprojects to update
            if not args["--skipNestedSubprojects"]:

                nestedPrefixLookup = lambda x : config.get(f"nested-{x}", "prefix")
                if args["--allNestedSubprojects"]:
                    includedNestedSubprojectPrefixes = {nestedPrefixLookup(sub):True for sub in allNestedSubprojects}
                elif args["--add"] or args["--rm"] or args["--ensureCIReposPresent"]:
                    includedNestedSubprojectPrefixes = {sub:True for sub in config_parser_user.getAllActiveNestedSubprojectPrefixes(workspaceDir=self.workspace_dir)}
                    includedNestedSubprojectPrefixes.update({nestedPrefixLookup(sub):True for sub in addedNestedSubprojects})
                    includedNestedSubprojectPrefixes.update({nestedPrefixLookup(sub):False for sub in rmNestedSubprojects})
                else:
                    includedNestedSubprojectPrefixes = self.defineActiveNestedSubprojects()

            if root:
                self.uvManager.finalize()
                root.mainloop()
                if self.uvManager.saved is False:
                    logging.info("Not changing working view.")
                    return False
                # If --all/--add/--rm is used, only consider the
                # command line for the included subprojects.
                if self.uvManager.includedSubmodules is None:
                    logging.info("Submodule changes from GUI ignored")
                else:
                    includedSubmodules = self.uvManager.includedSubmodules
                if self.uvManager.includedNestedSubprojects is None:
                    logging.info("Nested subproject changes from GUI ignored")
                else:
                    includedNestedSubprojectPrefixes = self.uvManager.includedNestedSubprojects
                try:
                    root.destroy()
                except:
                    pass

            if hasSubmodules:
                initStr = ""
                deinitStr = ""
                rmCachedStr = ""
                resetStr = ""
                for submodule, nowActive in includedSubmodules.items():
                    if nowActive:
                        initStr += f' {submodule}'
                    else:
                        deinitStr += f' {submodule}'
                        rmCachedStr += f' {submodule}'
                        resetStr += f' {submodule}'
                if args["-f"] and deinitStr:
                    deinitStr = "-f"+deinitStr

                logging.info("Configuring submodules...")
                logging.info("Initializing submodules...")
                git.submodule(f"init {initStr.strip()}",
                              execution_path=self.workspace_dir)
                if deinitStr:
                    logging.info(f"Deiniting submodules that were not requested... ({deinitStr})")
                    done = False
                    while not done:
                        try:
                            git.submodule(f"deinit {deinitStr.strip()}",
                                          execution_path=self.workspace_dir)
                            done = True
                        except grape_errors.GrapeGitError as e:
                            if "the following file has local modifications" in e.gitOutput.lower():
                                logging.error(e.gitOutput)
                                logging.error(
                                    "A submodule that you wanted to remove " +
                                    "has local modifications. " +
                                    "Use grape uv -f to force removal.")
                                return False
                            elif "use 'rm -rf' if you really want to remove it including all of its history" in e.gitOutput.lower():
                                if not args["-f"]:
                                    raise e
                                # it is safe to move the .git of the submodule to the .git/modules area of the workspace...
                                module = None
                                for l in e.gitOutput.lower().split('\n'):
                                    if "submodule work tree" in l and "contains a .git directory" in l:
                                        module = l.split("'")[1]
                                        break
                                if module:
                                    src = os.path.join(module, ".git")
                                    dest =  os.path.join(self.workspace_dir, ".git", "modules", module)
                                    logging.info(f"Moving {src} to {dest}")
                                    shutil.move(src, dest)
                                else:
                                    raise e
                            else:
                                raise e
                    git.rm(f"--cached {rmCachedStr}",
                           execution_path=self.workspace_dir)
                    git.reset(f" {resetStr}", execution_path=self.workspace_dir)

                if initStr:
                    logging.info(f"Updating active submodules...({initStr})")
                    git.submodule("update", execution_path=self.workspace_dir)

            # handle nested subprojects
            if not args["--skipNestedSubprojects"]:
                reverseLookupByPrefix = {nestedPrefixLookup(sub) : sub for sub in allNestedSubprojects}
                userConfig = config_parser_user.GrapeConfigParserUser(workspace_dir=self.workspace_dir, read_global=False)
                updatedActiveList = []
                for subproject, nowActive in includedNestedSubprojectPrefixes.items():
                    subprojectName = reverseLookupByPrefix[subproject]
                    section = f"nested-{subprojectName}"
                    userConfig.ensureSection(section)
                    subproject = git.gitPathToOsPath(subproject)
                    previouslyActive = userConfig.getboolean(section, "active")
                    previouslyActive = previouslyActive and os.path.exists(os.path.join(self.workspace_dir, subproject, ".git"))
                    userConfig.set(section, "active", "True" if previouslyActive else "False")
                    if nowActive and previouslyActive:
                        updatedActiveList.append(subprojectName)

                    if nowActive and not previouslyActive:
                        logging.info(f"Activating Nested Subproject {subproject}")
                        if not addSubproject.AddSubproject.activateNestedSubproject(subprojectName, userConfig, self.workspace_dir):
                            logging.info(f"Can't activate {subprojectName}. Exiting...")
                            return False

                        updatedActiveList.append(subprojectName)

                    if not nowActive and not previouslyActive:
                        pass
                    if not nowActive and previouslyActive:
                        #remove the subproject
                        subprojectdir = os.path.join(self.workspace_dir, subproject)
                        proceed = args["-f"] or \
                                  utility.userInput(f"About to delete all contents in {subproject}. " +
                                                    "Any uncommitted changes, committed changes that have " +
                                                    "not been pushed, or ignored files will be lost.  Proceed?", 'n')
                        if proceed:
                            def force_rm(func, path, excinfo):
                                os.chmod(path, stat.S_IWRITE)
                                func(path)
                            shutil.rmtree(subprojectdir, onerror=force_rm)
                userConfig.setActiveNestedSubprojects(updatedActiveList)
                config_parser_global.writeConfig(userConfig, os.path.join(self.workspace_dir, ".git", ".grapeuserconfig"))

        checkoutArgs = "-b" if args["-b"] else ""
        branch = args["--branchName"] if args["--branchName"] else git.currentBranch(execution_path=self.workspace_dir)

        safeSwitchWorkspaceToBranch(
            branch, checkoutArgs, sync,
            runInOuter=not args["--skipTopLevel"],
            skipSubmodules=args["--skipSubmodules"],
            runInSubprojects=not args["--skipNestedSubprojects"],
            workspace_dir=self.workspace_dir)


        if args["--generateSHAList"]:
            nested_subprojects = config_parser_user.getAllActiveNestedSubprojectPrefixes(workspaceDir=self.workspace_dir)
            sha_dict = {}
            for sub in nested_subprojects:
                sha_dict[sub] = git.SHA(execution_path=os.path.join(self.workspace_dir,sub))
            # write dict in a pickle file
            with open(os.path.join(self.workspace_dir,"GRAPE_PROJECT_SHA.json"),'w') as f:
                json.dump(sha_dict, f)

        return True

    def setDefaultConfig(self, config):
        config.ensureSection(self.SECTION_WORKSPACE)
        config.set(self.SECTION_WORKSPACE, "submodulepublicmappings", "?:master")
        config.set(self.SECTION_WORKSPACE, "CIRepos", " ")


def ensureLocalUpToDateWithRemote(repo='', branch='master', *, workspace_dir):
    logging.info(f"Ensuring local branch {branch} in {repo} is up to date with origin")
    # attempt to fetch the requested branch
    try:
        git.fetch("origin", f"{branch}:{branch}", execution_path=repo)
    except grape_errors.GrapeGitError as e:
        if "refusing to fetch into current branch" in e.gitOutput.lower():
            try:
                git.pull(f"origin {branch}", execution_path=repo)
            except:
                logging.error(e.gitOutput)
        else:
            git.info(f"Fetch to update {branch} in {repo} failed : {e.gitOutput}\n\tContinuing...")
        pass

    if git.currentBranch(execution_path=repo) == branch:
        return

    if not git.hasBranch(branch, execution_path=repo):
        # switch to corresponding public branch if the branch does not exist
        public = config_parser_workspace.GrapeConfigParserWorkspace(workspace_dir).getPublicBranchFor(branch)
        # figure out if this is a submodule
        relpath = os.path.relpath(repo, workspace_dir)
        # if this is a submodule, get the appropriate public mapping
        if utility.win_path_to_linux_path(relpath) in git.getAllSubmoduleURLMap(execution_path=workspace_dir).keys():
            public = config_parser_workspace.GrapeConfigParserWorkspace(workspace_dir).getMapping(Option.SECTION_WORKSPACE, "submodulepublicmappings")[public]
        logging.info(f"Branch {branch} does not exist in {repo}, switching to {public} and detaching")
        git.checkout(public, execution_path=repo)
        git.pull(f"origin {public}", execution_path=repo)
        git.checkout("--detach HEAD", execution_path=repo)

def cleanupPush(repo='', branch='', args='none', *, execution_path):
    logging.info(f"Attempting push of local {branch} in {repo}")
    git.push(f"origin {branch}", execution_path=repo)


def handleCleanupPushMRE(mre):
    for e, repo, branch in zip(mre.exceptions(), mre.repos(), mre.branches()):
        try:
            raise e
        except grape_errors.GrapeGitError as e2:
            logging.error(f"Local and remote versions of {branch} may have diverged in {repo}")
            logging.error(f"{e2.gitOutput}")
            logging.error("Use grape pull to merge the remote version into the local version.")

def handleEnsureLocalUpToDateMRE(mre):
    _pushBranch = False
    _skipPush = False
    cleanupPushArgs = []
    for e1, repo, branch in zip(mre.exceptions(), mre.repos(), mre.branches()):
        try:
            raise e1
        except grape_errors.GrapeGitError as e:
            if ("[rejected]" in e.gitOutput.lower() and "(non-fast-forward)" in e.gitOutput.lower()) or e.could_not_find_remote_ref():
                if e.could_not_find_remote_ref():
                    if not _pushBranch:
                        logging.info(f"No remote reference to {branch} in {repo}'s origin. You may want to push this branch.")
                else:
                    logging.info(f"Fetch of {branch} rejected as non-fast-forward in repo {repo}")
                pushBranch = _pushBranch
                if _skipPush:
                    pushBranch = False
                elif not pushBranch:
                    pushBranch =  utility.userInput("Would you like to push your local branch? \n"
                                                    "(select 'a' to say yes for (a)ll subprojects, 's' to (s)kip push for all subprojects)"
                                                    "\n(y,n,a,s)", 'y')

                if str(pushBranch).lower()[0] == 'a':
                    _pushBranch = True
                    pushBranch = True
                if str(pushBranch).lower()[0] == 's':
                    _skipPush = True
                    pushBranch = False
                if pushBranch:

                    cleanupPushArgs.append((repo, branch, None))
                else:
                    logging.info(f"Skipping push of local {branch} in {repo}")

            elif e.commError:
                logging.error(f"Could not update {branch} from origin due" +
                              " to a connectivity issue. Checking out most" +
                              " recent\nlocal version. ")
            else:
                raise(e)

    # do another MRC launch to do any follow up pushes that were requested.
    launcher = multi_repo_cmd_launcher.MultiRepoCommandLauncher(
        cleanupPush, listOfRepoBranchArgTuples=cleanupPushArgs,
        workspace_dir=mre.workspace_dir)
    launcher.launchFromWorkspaceDir(handleMRE=handleCleanupPushMRE)
    return

def safeSwitchWorkspaceToBranch(branch, checkoutArgs, sync, *, workspace_dir, runInOuter=True, skipSubmodules=False, runInSubprojects=True ):
    # Ensure local branches that you are about to check out are up to date with the remote
    if sync:
        launcher = multi_repo_cmd_launcher.MultiRepoCommandLauncher(
            ensureLocalUpToDateWithRemote, branch=branch,
            runInOuter=runInOuter, skipSubmodules=skipSubmodules, runInSubprojects=runInSubprojects,
            globalArgs=[checkoutArgs], workspace_dir=workspace_dir)
        launcher.launchFromWorkspaceDir(handleMRE=handleEnsureLocalUpToDateMRE)
    # Do a checkout
    # Pass False instead of sync since if sync is True ensureLocalUpToDateWithRemote will have already performed the fetch
    launcher = multi_repo_cmd_launcher.MultiRepoCommandLauncher(
        checkout.handledCheckout, branch=branch,
        runInOuter=runInOuter, skipSubmodules=skipSubmodules, runInSubprojects=runInSubprojects,
        globalArgs=[checkoutArgs, False], workspace_dir=workspace_dir)
    launcher.launchFromWorkspaceDir(handleMRE=checkout.handleCheckoutMRE)


# Class for selecting subprojects in a workspace
class UVManager:
    def __init__(self, master, **kwargs):
        height = kwargs.get('height', 0)
        width  = kwargs.get('width', 0)

        # Saved lists of active subprojects (None if not saved)
        self.includedSubmodules = None
        self.includedNestedSubprojects = None
        self.saved = False

        self.master = master
        self.currentProjectIndex = None

        # 0 is submodules
        # 1 is nested subprojects
        self.activeSets = [ None, None ]
        self.inactiveSets = [ None, None ]
        self.originalActiveSets = [ None, None ]

        self.currentFrame = None
        self.currentActiveList = None
        self.currentInactiveList = None

        # Colors
        self.fginit     = kwargs.get('fginit', 'black')
        self.bginit     = kwargs.get('bginit', 'gray')
        self.fgselected = kwargs.get('fgselected', 'black')
        self.bgselected = kwargs.get('bgselected', 'goldenrod')
        self.fgchanged   = kwargs.get('fgchanged', 'blue')

        self.active = []
        self.inactive = []
        # offset so first call to createFrame starts at 0
        self.currentColumn = -2
        self.currentRow = 0

        # Main resizable window
        self.main = Tk.PanedWindow(master, height=height, width=width, sashwidth=4)
        controlpanel = Tk.Frame()
        savebutton = Tk.Button(controlpanel, text="Save and Update", command = self.saveChanges)
        savebutton.grid(row=0, column=0)
        cancelbutton = Tk.Button(controlpanel, text="Cancel", command = self.master.destroy)
        cancelbutton.grid(row=0, column=1)
        controlpanel.grid(row=0, column=0)

    # Save changes and exit
    def saveChanges(self):
        if self.activeSets[0] is not None:
            self.saved = True
            self.includedSubmodules = {}
            for sub in self.activeSets[0]:
                self.includedSubmodules[sub] = True
            for sub in self.inactiveSets[0]:
                self.includedSubmodules[sub] = False
        if self.activeSets[1] is not None:
            self.saved = True
            self.includedNestedSubprojects = {}
            for sub in self.activeSets[1]:
                self.includedNestedSubprojects[sub] = True
            for sub in self.inactiveSets[1]:
                self.includedNestedSubprojects[sub] = False
        self.master.destroy()

    # Save the original set of active subprojects and sort the last section
    def finalize(self):
        # sort the last section
        self.resortList(self.currentActiveList)
        self.resortList(self.currentInactiveList)

        # save the original state
        for i in [0, 1]:
            self.originalActiveSets[i] = set()
            if self.activeSets[i]:
               for sub in self.activeSets[i]:
                   self.originalActiveSets[i].add(sub)


    # Start a new frame for different project type
    def createFrame(self, projectType):
        self.currentRow = 2
        self.currentColumn = self.currentColumn + 2
        frame = Tk.Frame()
        label = Tk.Label(frame, text=f"Select {projectType}s")
        label.grid()
        self.master.grid_rowconfigure(self.currentRow, weight=1)
        self.master.grid_columnconfigure(self.currentColumn, weight=1)
        self.master.grid_columnconfigure(self.currentColumn+1, weight=1)
        frame.grid(row=1, column=self.currentColumn, columnspan=2, sticky="nsew")
        if projectType == "submodule":
            self.currentProjectIndex = 0
        elif projectType == "nested subproject":
            self.currentProjectIndex = 1

    # Start a new section for a different directory
    def createSection(self, directory = ""):
        directory_name = "top level" if directory == "" else directory
        
        # sort the previous section (if any)
        self.resortList(self.currentActiveList)
        self.resortList(self.currentInactiveList)

        activepanel = Tk.Frame()
        activelabel = Tk.Label(activepanel, text=f"Active in {directory_name}")
        activescroll = Tk.Scrollbar(activepanel, width=10)
        activelist = Tk.Listbox(activepanel, background=self.bginit, foreground=self.fginit, selectbackground=self.bgselected, selectforeground=self.fgselected, yscrollcommand=activescroll.set, selectmode=Tk.SINGLE)
        activescroll.config(command=activelist.yview)
        activescroll.grid(row=2, column=0, sticky=Tk.N+Tk.S)
        activelabel.grid(row=0, column=0, columnspan=2)
        activelist.grid(row=2, column=1)
        activepanel.grid(row=self.currentRow, column=self.currentColumn)

        activepanel.grid_rowconfigure(2, weight=1)
        activepanel.grid_columnconfigure(1, weight=1)
        activelist.grid(row=2, column=1, sticky="nsew")
        activepanel.grid(row=self.currentRow, column=self.currentColumn, sticky="nsew")
        self.currentActiveList = activelist

        inactivepanel = Tk.Frame()
        inactivelabel = Tk.Label(inactivepanel, text=f"Inactive in {directory_name}")
        inactivescroll = Tk.Scrollbar(inactivepanel, width=10)
        inactivelist = Tk.Listbox(inactivepanel, background=self.bginit, foreground=self.fginit, selectbackground=self.bgselected, selectforeground=self.fgselected, yscrollcommand=inactivescroll.set, selectmode=Tk.SINGLE)
        inactivescroll.config(command=inactivelist.yview)
        inactivescroll.grid(row=2, column=0, sticky=Tk.N+Tk.S)
        inactivelabel.grid(row=0, column=0, columnspan=2)
        inactivepanel.grid_rowconfigure(2, weight=1)
        inactivepanel.grid_columnconfigure(1, weight=1)
        inactivelist.grid(row=2, column=1, sticky="nsew")
        inactivepanel.grid(row=self.currentRow, column=self.currentColumn+1, sticky="nsew")
        self.currentInactiveList = inactivelist

        self.currentRow = self.currentRow + 2

        index = self.currentProjectIndex
        activelist.bind("<Double-Button-1>", lambda e: self.deactivateProject(directory, activelist, inactivelist,
                                                                              self.activeSets[index], self.inactiveSets[index], self.originalActiveSets[index]))
        inactivelist.bind("<Double-Button-1>", lambda e: self.activateProject(directory, activelist, inactivelist,
                                                                              self.activeSets[index], self.inactiveSets[index], self.originalActiveSets[index]))

        activeall = Tk.Button(activepanel, text="activate all", borderwidth=0, foreground="darkblue",
                              command = lambda : self.activateAll(directory, activelist, inactivelist,
                                                                  self.activeSets[index], self.inactiveSets[index], self.originalActiveSets[index]))
        activeall.grid(row=1, column=0, columnspan=2)
        inactiveall = Tk.Button(inactivepanel, text="deactivate all", borderwidth=0, foreground="darkblue",
                                command = lambda : self.deactivateAll(directory, activelist, inactivelist,
                                                                      self.activeSets[index], self.inactiveSets[index], self.originalActiveSets[index]))
        inactiveall.grid(row=1, column=0, columnspan=2)


    # Create an entry for a subproject
    def createEntry(self, directory, subproject, isActive):
        if self.activeSets[self.currentProjectIndex] is None:
            self.activeSets[self.currentProjectIndex] = set()
        if self.inactiveSets[self.currentProjectIndex] is None:
            self.inactiveSets[self.currentProjectIndex] = set()

        if isActive:
            self.currentActiveList.insert(Tk.END, subproject)
            self.activeSets[self.currentProjectIndex].add(os.path.join(directory,subproject))
        else:
            self.currentInactiveList.insert(Tk.END, subproject)
            self.inactiveSets[self.currentProjectIndex].add(os.path.join(directory,subproject))

    # Activate selected project
    def activateProject(self, directory, activelist, inactivelist, activeset, inactiveset, originalactiveset):
        index = inactivelist.index(Tk.ACTIVE)
        entry = inactivelist.get(index)
        inactivelist.delete(index)
        inactiveset.remove(os.path.join(directory,entry))
        activelist.insert(Tk.END, entry)
        activeset.add(os.path.join(directory,entry))
        self.resortList(activelist, originalactiveset, self.fginit, self.fgchanged, directory)
        self.resortList(inactivelist, originalactiveset, self.fgchanged, self.fginit, directory)
        self.master.update()

    # Deactivate selected project
    def deactivateProject(self, directory, activelist, inactivelist, activeset, inactiveset, originalactiveset):
        index = activelist.index(Tk.ACTIVE)
        entry = activelist.get(index)
        activelist.delete(index)
        activeset.remove(os.path.join(directory,entry))
        inactivelist.insert(Tk.END, entry)
        inactiveset.add(os.path.join(directory,entry))
        self.resortList(activelist, originalactiveset, self.fginit, self.fgchanged, directory)
        self.resortList(inactivelist, originalactiveset, self.fgchanged, self.fginit, directory)
        self.master.update()

    # Activate all projects in the section
    def activateAll(self, directory, activelist, inactivelist, activeset, inactiveset, originalactiveset):
        entries = inactivelist.get(0, Tk.END)
        inactivelist.delete(0,Tk.END)
        for entry in entries:
            activelist.insert(Tk.END, entry)
            activeset.add(os.path.join(directory,entry))
            inactiveset.remove(os.path.join(directory,entry))
        self.resortList(activelist, originalactiveset, self.fginit, self.fgchanged, directory)
        self.resortList(inactivelist, originalactiveset, self.fgchanged, self.fginit, directory)
        self.master.update()

    # Deactivate all projects in the section
    def deactivateAll(self, directory, activelist, inactivelist, activeset, inactiveset, originalactiveset):
        entries = activelist.get(0, Tk.END)
        activelist.delete(0,Tk.END)
        for entry in entries:
            inactivelist.insert(Tk.END, entry)
            inactiveset.add(os.path.join(directory,entry))
            activeset.remove(os.path.join(directory,entry))
        self.resortList(activelist, originalactiveset, self.fginit, self.fgchanged, directory)
        self.resortList(inactivelist, originalactiveset, self.fgchanged, self.fginit, directory)
        self.master.update()

    # Resort and format the list boxes
    def resortList(self, listbox, originalset = None, inSetColor = None, notInSetColor = None, directory = ""):
        if listbox:
           entries = listbox.get(0, Tk.END)
           listbox.delete(0, Tk.END)
           for entry in sorted(entries):
               listbox.insert(Tk.END, entry)
               if originalset is not None:
                   if os.path.join(directory,entry) in originalset:
                       listbox.itemconfig(Tk.END, fg=inSetColor)
                   else:
                       listbox.itemconfig(Tk.END, fg=notInSetColor)
